# 1- Imports

In [1]:
import pandas as pd
import numpy as np

# 2- Load data

In [2]:
df_fifa22 = pd.read_csv("./data/players_22.csv")
df_goles22 = pd.read_csv("./data/datos_reales_15_10_2024_id.csv")

# 3- Clean Goals data

In [ ]:
df_goles22.drop(columns=["Unnamed: 0"], inplace=True)
df_goles22 = df_goles22[df_goles22["goles"] > 0]
df_goles22.reset_index(drop=True, inplace=True)

In [61]:
df_goles22.head()

,nombre,match_id,posicion,pj,pt,goles,asistencias,tarjetas,equipo,porteria
0,K. Mbappé,231747,delantero,35,34,28,17,10,psg,0
1,K. Benzema,165153,delantero,32,31,27,12,0,real_madrid,0
2,C. Immobile,192387,delantero,31,31,27,2,4,lazio,0
3,W. Ben Yedder,199451,delantero,37,29,25,5,3,monaco,0
4,M. Salah,209331,delantero,35,30,23,13,1,liverpool,0

# 4- Data viz

In [18]:
display(df_goles22.info());

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1061 entries, 0 to 1060
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nombre       1061 non-null   object
 1   match_id     1061 non-null   int64
 2   posicion     1061 non-null   object
 3   pj           1061 non-null   int64
 4   pt           1061 non-null   int64
 5   goles        1061 non-null   int64
 6   asistencias  1061 non-null   int64
 7   tarjetas     1061 non-null   int64
 8   equipo       1061 non-null   object
 9   porteria     1061 non-null   int64
dtypes: int64(7), object(3)
memory usage: 83.0+ KB

None

In [22]:
l = df_fifa22.columns.to_list()
for i in l:
    print(i)

sofifa_id
player_url
short_name
long_name
player_positions
overall
potential
value_eur
wage_eur
age
dob
height_cm
weight_kg
club_team_id
club_name
league_name
league_level
club_position
club_jersey_number
club_loaned_from
club_joined
club_contract_valid_until
nationality_id
nationality_name
nation_team_id
nation_position
nation_jersey_number
preferred_foot
weak_foot
skill_moves
international_reputation
work_rate
body_type
real_face
release_clause_eur
player_tags
player_traits
pace
shooting
passing
dribbling
defending
physic
attacking_crossing
attacking_finishing
attacking_heading_accuracy
attacking_short_passing
attacking_volleys
skill_dribbling
skill_curve
skill_fk_accuracy
skill_long_passing
skill_ball_control
movement_acceleration
movement_sprint_speed
movement_agility
movement_reactions
movement_balance
power_shot_power
power_jumping
power_stamina
power_strength
power_long_shots
mentality_aggression
mentality_interceptions
mentality_positioning
mentality_vision
mentality_penalties
mentality_composure
defending_marking_awareness
defending_standing_tackle
defending_sliding_tackle
goalkeeping_diving
goalkeeping_handling
goalkeeping_kicking
goalkeeping_positioning
goalkeeping_reflexes
goalkeeping_speed
ls
st
rs
lw
lf
cf
rf
rw
lam
cam
ram
lm
lcm
cm
rcm
rm
lwb
ldm
cdm
rdm
rwb
lb
lcb
cb
rcb
rb
gk
player_face_url
club_logo_url
club_flag_url
nation_logo_url
nation_flag_url

In [11]:
df_goles22.head()

,nombre,match_id,posicion,pj,pt,goles,asistencias,tarjetas,equipo,porteria
0,K. Mbappé,231747,delantero,35,34,28,17,10,psg,0
1,K. Benzema,165153,delantero,32,31,27,12,0,real_madrid,0
2,C. Immobile,192387,delantero,31,31,27,2,4,lazio,0
3,W. Ben Yedder,199451,delantero,37,29,25,5,3,monaco,0
4,M. Salah,209331,delantero,35,30,23,13,1,liverpool,0

# 5- Limpiar y filtrar FIFA Data

## 0- Rename cols

In [94]:
df_goles22

,nombre,match_id,posicion,pj,pt,goles,asistencias,tarjetas,equipo,porteria
0,K. Mbappé,231747,delantero,35,34,28,17,10,psg,0
1,K. Benzema,165153,delantero,32,31,27,12,0,real_madrid,0
2,C. Immobile,192387,delantero,31,31,27,2,4,lazio,0
3,W. Ben Yedder,199451,delantero,37,29,25,5,3,monaco,0
4,M. Salah,209331,delantero,35,30,23,13,1,liverpool,0
...,...,...,...,...,...,...,...,...,...,...
1056,M. Udol,0,defensa,12,11,1,0,0,metz,0
1057,Kiki Kouyaté,0,defensa,30,30,1,0,9,metz,0
1058,V. Pajot,0,mediocentro,30,27,1,0,7,metz,0
1059,E. Mexer,0,defensa,16,14,1,0,2,girondins_bordeaux,0
1060,E. Kwateng,0,defensa,29,22,1,0,5,girondins_bordeaux,0

In [108]:
df_fifa22 = df_fifa22.rename(columns={"sofifa_id":"match_id"})

## 1- Filtrar por ligas ("Italian Serie A", "French Ligue 2","English Premier League","Spain Primera Division","German 1. Bundesliga")

In [ ]:

df_fifa22 = df_fifa22[df_fifa22["league_name"].isin(["Italian Serie A", "French Ligue 2","English Premier League","Spain Primera Division","German 1. Bundesliga"])]

df_fifa22.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
55,208334,https://sofifa.com/player/208334/jonas-hector/...,J. Hector,Jonas Hector,"CDM, LB",78,78,10000000.0,28000.0,31,...,75+2,75+2,75+2,75+2,19+2,https://cdn.sofifa.net/players/208/334/22_120.png,https://cdn.sofifa.net/teams/31/60.png,https://cdn.sofifa.net/flags/de.png,NaN,https://cdn.sofifa.net/flags/de.png
56,225126,https://sofifa.com/player/225126/ellyes-skhiri...,E. Skhiri,Ellyes Joris Skhiri,"CDM, CM",77,79,11500000.0,26000.0,26,...,74+2,74+2,74+2,74+2,20+2,https://cdn.sofifa.net/players/225/126/22_120.png,https://cdn.sofifa.net/teams/31/60.png,https://cdn.sofifa.net/flags/de.png,NaN,https://cdn.sofifa.net/flags/tn.png
57,200316,https://sofifa.com/player/200316/timo-horn/220002,T. Horn,Timo Horn,GK,76,78,6500000.0,21000.0,28,...,28+2,28+2,28+2,27+2,75+2,https://cdn.sofifa.net/players/200/316/22_120.png,https://cdn.sofifa.net/teams/31/60.png,https://cdn.sofifa.net/flags/de.png,NaN,https://cdn.sofifa.net/flags/de.png
58,195038,https://sofifa.com/player/195038/florian-kainz...,F. Kainz,Florian Kainz,"LM, RM",75,75,5500000.0,27000.0,28,...,48+2,48+2,48+2,54+2,18+2,https://cdn.sofifa.net/players/195/038/22_120.png,https://cdn.sofifa.net/teams/31/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1322/60.png,https://cdn.sofifa.net/flags/at.png
59,200318,https://sofifa.com/player/200318/mark-uth/220002,M. Uth,Mark Uth,"CAM, CF, ST",75,75,5500000.0,27000.0,29,...,52+2,52+2,52+2,57+2,17+2,https://cdn.sofifa.net/players/200/318/22_120.png,https://cdn.sofifa.net/teams/31/60.png,https://cdn.sofifa.net/flags/de.png,NaN,https://cdn.sofifa.net/flags/de.png

## 2- Quitar columnas que sobran

In [112]:
columns_to_drop = ["player_url","club_jersey_number","club_loaned_from","club_contract_valid_until","nation_position","nation_jersey_number","player_face_url","club_logo_url","club_flag_url","nation_logo_url","nation_flag_url"]
ns_cols = ["ls""st""rs""lw""lf""cf""rf""rw""lam""cam""ram""lm""lcm""cm""rcm""rm","lwb"]
desired_columns = ["match_id","short_name","shooting","pace","attacking_crossing","attacking_finishing","attacking_heading_accuracy","attacking_volleys","skill_dribbling","skill_curve","skill_fk_accuracy","skill_ball_control","movement_acceleration","movement_sprint_speed","movement_agility","power_shot_power","power_jumping","power_stamina","power_strength","power_long_shots","mentality_aggression","mentality_positioning","mentality_vision","mentality_penalties","mentality_composure"]

In [97]:
df_fifa22.iloc[180:200,0:20].head()

,match_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,club_team_id,club_name,league_name,league_level,club_position,club_jersey_number,club_loaned_from
660,205378,https://sofifa.com/player/205378/baptiste-vale...,B. Valette,Baptiste Valette,GK,64,65,475000.0,2000.0,28,1992-09-01,185,80,1823.0,AS Nancy Lorraine,French Ligue 2,2.0,SUB,1.0,NaN
661,205388,https://sofifa.com/player/205388/edmond-akichi...,E. Akichi,Ogou Edmond Akichi,"CDM, CM",64,64,400000.0,2000.0,31,1990-04-24,178,75,1823.0,AS Nancy Lorraine,French Ligue 2,2.0,SUB,24.0,NaN
662,221270,https://sofifa.com/player/221270/gregoire-lefe...,G. Lefebvre,Grégoire Lefebvre,"CDM, CM",64,65,600000.0,2000.0,27,1994-05-13,175,68,1823.0,AS Nancy Lorraine,French Ligue 2,2.0,SUB,6.0,NaN
663,224777,https://sofifa.com/player/224777/rosario-latou...,R. Latouchent,Rosario Latouchent,"LB, RB",64,68,750000.0,2000.0,25,1996-03-21,180,72,1823.0,AS Nancy Lorraine,French Ligue 2,2.0,SUB,11.0,NaN
664,238060,https://sofifa.com/player/238060/nathan-trott/...,N. Trott,Nathan Trott,GK,64,74,1100000.0,8000.0,22,1998-11-21,188,75,1823.0,AS Nancy Lorraine,French Ligue 2,2.0,GK,16.0,West Ham United

In [113]:
df = df_fifa22[desired_columns]

# 5- Join tables

In [117]:
df[df["goles"].isna()]

,match_id,short_name,shooting,pace,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_volleys,skill_dribbling,skill_curve,...,mentality_composure,nombre,posicion,pj,pt,goles,asistencias,tarjetas,equipo,porteria
0,208334,J. Hector,60.0,59.0,78,55,67,51,74,65,...,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,225126,E. Skhiri,69.0,58.0,67,69,73,60,73,72,...,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,200316,T. Horn,NaN,NaN,19,13,14,14,20,12,...,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,195038,F. Kainz,73.0,72.0,75,75,55,55,77,69,...,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,200318,M. Uth,77.0,73.0,69,75,67,74,76,80,...,71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2965,261032,J. Hodge,45.0,59.0,49,37,48,37,54,43,...,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2966,251590,L. Richards,41.0,61.0,48,38,52,35,47,46,...,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2967,253461,L. Cundle,51.0,61.0,49,49,38,46,55,51,...,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2968,258532,C. Carty,54.0,65.0,46,53,50,50,51,49,...,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2969,244507,P. Estrada,43.0,62.0,41,41,49,34,51,52,...,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
df = pd.merge(df,df_goles22,on="match_id",how="left")

# 6- Feature engineering

## 1- Fill NAN

## 2- Get value from Features:
 - international_reputation	
 - work_rate
 - body_type
 - real_face
 - release_clause_eur
 - player_tags
 - ns_cols